# Generated by Django 3.0.2 on 2021-02-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/doc.txt'),
        ),
    ]
