# Generated by Django 3.0.2 on 2021-02-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='qac',
            name='idx',
            field=models.IntegerField(blank=True, default=0, verbose_name='ID'),
        ),
    ]
