# Generated by Django 3.0.2 on 2021-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_qac_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1024, verbose_name='ドキュメント')),
            ],
        ),
        migrations.RemoveField(
            model_name='qac',
            name='context',
        ),
    ]
